### PR TITLE
KFSPTS-28557 remove Award node for purchase order amendment documents

### PR DESCRIPTION
**Pull request by jhulslander**
I have made changes to the route node logic in the document type XML.  I wasn't sure if I should remove the category statuses "Disapproved C and G" and "Awaiting C and G Approval".  I was leaning toward not to avoid search related problems, but I am not certain.
The user story references some responsibilities.  Should I add sub tasks for Nicole to deactivate those?

### CODE REVIEW

**Comment by cah292** [comment]
I think it's fine to keep the "Disapproved C and G" and "Awaiting C and G Approval" status definitions in place, for consistency with the other PO document variants.

As for whether to add responsibility inactivation sub-tasks, I'll add a follow-up note with more details.

**Review by cah292 — COMMENTED** [review]
The POA workflow XML changes look good. There are a few follow-up tasks that are still needed, though, but we'll need more functional input as to the timing for implementing them:

1. I agree with the note in the PR's description that the KIM responsibilities for the removed nodes should be inactivated.
2. Also, I would suggest updating the `CuPurchaseOrderAmendmentDocument.answerSplitNodeQuestion()` method to remove the references to the deleted nodes.

For the existing Enroute POA documents that predate this workflow change, do the functionals expect them to be finalized prior to (or at the time of) ingesting this workflow XML into PROD? If such Enroute docs are expected to take several days/weeks to finish routing, then the code and responsibility cleanup items above may need to be deferred to a follow-up ticket.

**Comment by jhulslander** [comment]
Chad,
Thanks for the feedback, I will ping Janet concerning the thoughts

**Comment by jhulslander** [comment]
@cah292  Based on Janet's feed back, I created KFSPTS-29735 to handle the permission changes and code changes to be done after POA documents created on the old workflow have been finalized.  I added a note to KFSPTS-29666 to capture a list of documents when the new workflow XML is ingested to prod.

Please update the follow up user story if you think I missed any details.

This is ready for review again

**Review by cah292 — APPROVED** [review]
Changes look good and I'm fine with the appropriate follow-up items being deferred to a future user story. Sorry for the delay in re-reviewing this.

Merging.

**Pull request merged**
