### PR TITLE
KFSPTS-10267 inherit sub fund group code dd definition from Sub Fund …

### PR DESCRIPTION
**Pull request by db483**
…Group object; this willalso fix the 6 characters exact length restriction

### CODE REVIEW

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
The changes look fine, but the unit tests are failing, I kicked off another run just to see if something "weird" caused the failures.

**Comment by jhulslander** [comment]
The test suite failed again, looks like spring couldn't load.

**Comment by db483** [comment]
Hmm, I see this exception:
Internal Exception: java.sql.SQLException: SQLException in StandardPoolDataSource:getConnection exception: java.sql.SQLException: SQLException in StandardPoolDataSource:getConnection no connection available java.sql.SQLException: Cannot get connection for URL jdbc:oracle:thin:@//utest.csbkl3q8fphu.us-east-1.rds.amazonaws.com:1521/UTEST : IO Error: Unknown host specified

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
retest this please

**Pull request merged**
