### PR TITLE
KFSPTS-5956: reconcile post-5.3.1 changes

### PR DESCRIPTION
**Pull request by bhutchinson**

### CODE REVIEW

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
I don't see a problem with this, assuming the test suit should pass, I will merge after the unit tests pass, I requested Jenkins re-run them.

**Comment by bhutchinson** [comment]
Hmm, I see the unit test suite failed, let me investigate.

**Comment by bhutchinson** [comment]
retest this please

**Comment by bhutchinson** [comment]
Ok, there was a new db column added that we didn't have. I added it in UPUTEST and now the tests passed.

**Comment by jhulslander** [comment]
+1

**Pull request merged**
