### PR TITLE
KFSPTS-7616: Update base DD bean overrides with KFS 7.x changes.

### PR DESCRIPTION
**Pull request by cah292**
Our base DD attributes file was out-of-sync with the KFS 7.x version of it. This brings it up-to-date while still preserving our existing customizations to it.

If you think the file should be modified to only include the things that we have specifically overridden, please let me know.

### CODE REVIEW

**Comment by bhutchinson** [comment]
The changes look fine, but yes, if it's not too much effort, I think it would be better if the file could be modified to only include the things that we have specifically overridden, thanks.

**Comment by cah292** [comment]
That makes sense; I'll update the code accordingly. Thanks!

**Comment by cah292** [comment]
I've updated the bean file accordingly based on feedback. This is now ready for review again.

**Comment by cah292** [comment]
retest this please

**Pull request merged**
