### PR TITLE
KFSPTS-15174 upgrade to then 3/21/19, 3/28/19 version of financials

### PR DESCRIPTION
**Pull request by db483**

### CODE REVIEW

**Comment by db483** [comment]
retest this please

**Comment by jhulslander** [comment]
retest this please

**Comment by cah292** [comment]
As a result of the #775 changes from KFSPTS-15192, the non-updated section of CuContractsGrantsInvoiceDocumentServiceImpl is no longer present in our override. Thus, our code should automatically have the TOTAL_AMOUNT_DUE changes, and we don't need to include that file in this PR.

**Comment by cah292** [comment]
Closing since #778 has more up-to-date changes.

**Pull request closed without merging**
