### PR TITLE
KFSPTS-21430 back-port FINP-7396

### PR DESCRIPTION
**Pull request by jhulslander**
I brought in ContractsGrantsPaymentHistoryReportLookupableHelperServiceImpl as a new overlay item, then back-ported FINP-7396

### CODE REVIEW

**Review by cah292 — COMMENTED** [review]
FINP-7396 also included a change that replaced the use of ArPropertyConstants.RANGE_LOWER_BOUND_KEY_PREFIX with the use of KFSPropertyConstants.RANGE_LOWER_BOUND_KEY_PREFIX instead. (Both constants appear to have the same value, so it shouldn't matter which one we go with.) Should that change be included as well, or should that wait until we move to the actual 2021-03-11 version of the file?

Other than that, the changes look good.

**Comment by jhulslander** [comment]
I originally opted to not make that switch because they are the same value, but I think it would be good to switch from ArPropertyConstants to KFSPropertyConstants .... I will update this PR accordingly.  Thanks for noting

**Comment by jhulslander** [comment]
this is ready for review again

**Review by cah292 — APPROVED** [review]
Changes look good, and unit tests pass. Merging.

**Pull request merged**
