### PR TITLE
KFSPTS-26538 update spring-security-core to 5.6.9 and spring-core to 5.3.23

### PR DESCRIPTION
**Pull request by jhulslander**

### CODE REVIEW

**Review by cah292 — CHANGES_REQUESTED** [review]
The version change looks good, but it seems that the newer JAR is also pulling in some slightly newer versions of the regular Spring JARs ("5.3.23"). You might also need to update the "spring.version" property to match, unless you think we should stay at our current version (which would require adding exclusions to the security JAR dependency).

**Comment by jhulslander** [comment]
KualiCo is currently at 5.3.20.
I think it would make sense to update spring-core to 5.3.23 to be in line with what came with spring-security.  My primary thought would be to get ahead of potential future security vulnerabilities

**Comment by jhulslander** [comment]
This is ready for review again

**Review by cah292 — APPROVED** [review]
Changes look good and unit tests pass. Merging.

**Pull request merged**
