### PR TITLE
KFSPTS-6517: Merge latest changes from develop branch to post6-upgrade branch

### PR DESCRIPTION
**Pull request by bhutchinson**
The JIRA references Sprint 10, but there were actually more changes from develop that needed to be merged into the post6-upgrade branch because the last time I did that was on 7/12.

### CODE REVIEW

**Comment by bhutchinson** [comment]
@db483 & @jhulslander SInce this is a lot of commits we are merging from develop to post6-upgrade, I had to resolve several conflicts and both of you had worked on multiple large chunks of this, I wanted both of you to review. Thanks.

**Comment by bhutchinson** [comment]
retest this please

**Comment by jhulslander** [comment]
Changes look fine to me as well.

**Comment by jhulslander** [comment]
Checks have passed, and since Daniela thinks this is fine as well, I shall merge

**Pull request merged**
