### PR TITLE
KFSPTS-21650 do NOT merge this PR, creating to test kew upgrade unit …

### PR DESCRIPTION
**Pull request by jhulslander**
…testing

do NOT merge this PR, just testing

### CODE REVIEW

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
retest this

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
retest this please

**Comment by cah292** [comment]
@jhulslander I've reviewed the unit test errors that you had mentioned on one of the other tickets. I believe most or all of the failed tests can be fixed through a couple minor changes (one of which I will implement):

[1] I found an overlay in our upgraded cu-kfs code that was not properly updated with some of the non-KEW-related changes for the KEW-to-KFS upgrade patch. I will implement the needed changes and open up a new PR to get them merged.

[2] Due to the config changes we've made thus far for the KEW-to-KFS upgrade, we no longer need to override the "spring.source.files" property; we've set up other properties to include the appropriate custom source files. Please remove this property override from the KEW-to-KFS unit test config file.

**Comment by jhulslander** [comment]
@cah292  the properties files are located in secrets manager in AWS.  Take a look at kfs/jenkins/unittest/kfs-kew-config.properties and kfs/jenkins/unittest/kfs-kew-securities.properties .  I don't think spring.source.files is in either of these files.

**Comment by jhulslander** [comment]
retest this please

**Comment by cah292** [comment]
@jhulslander Thanks for the information.

While looking over the unit test failures again, I noticed in the logs that some of our custom PURAP-related files are not being loaded for some reason. I'm still looking into it further to determine if it's a bug in the cu-kfs code or not.

**Comment by cah292** [comment]
@jhulslander I think I found what was causing the problem, and I'm testing out a solution now. My comment on the #1125 PR has more details.

**Comment by cah292** [comment]
@jhulslander The tests are almost all working now on the other PR. A couple tests are receiving 403 responses from eSHOP-related endpoints, but after comparing the non-upgrade tests with the upgrade tests, these last few failures might just be the result of a configuration problem.

Can you please double-check the URL-related "b2b" properties in the upgrade unit test configs, to see if they line up with the URL configuration for the non-upgrade unit tests? We may have changed one or more of those URLs so that the PR unit test endpoints are different than the ones we use when running locally.

**Comment by jhulslander** [comment]
Yes, the B2B config wasn't the same as in https://github.com/CU-CommunityApps/config/blob/3e56ae831f5fdd2608475837e5c5a2f05c8f439f/security-kfs6.properties ... I've updated them

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
rest this please

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
retest this please

**Pull request closed without merging**
