### PR TITLE
KFSPTS-15268 add fix for issue with opening docs in Capital Asset sp…

### PR DESCRIPTION
**Pull request by db483**
…ace; changes brought in from FINP-5105 fix

### CODE REVIEW

**Comment by db483** [comment]
there were some changes to: performForceUppercaseCycleSafe

**Comment by db483** [comment]
Chad, you are right, the changes to performForceUppercaseCycleSafe are not in.

**Comment by db483** [comment]
I have removed the BusinessObjectDictionaryService as we discussed in slack. It has no relevant changes.

**Comment by cah292** [comment]
As per the discussion in Slack, this change will be merged in a new PR instead, so that it can be merged to develop without commit conflicts.

**Pull request closed without merging**
