### PR TITLE
KFSPTS-15091 enable YEBA in create accounting documents job

### PR DESCRIPTION
**Pull request by jhulslander**

### CODE REVIEW

**Comment by jhulslander** [comment]
Since YEBA is very much like BA, I didn't think it was required.  If you think more tests would be preferable, let me know and I can add some

**Comment by cah292** [comment]
I think a few more simple test cases would be a good addition, just to make sure the YEBA processing is properly handling the month amounts and such.

**Comment by jhulslander** [comment]
OK, I shall work on that tomorrow

**Comment by jhulslander** [comment]
I've added additional unit tests for multiple YEBA docs in one file, and a YEBA doc in a multi doc type file.  This is ready for review again

**Pull request merged**
