### PR TITLE
KFSPTS-29106 fix CG Reporting Code Inquiry

### PR DESCRIPTION
**Pull request by db483**

### CODE REVIEW

**Review by nkimble — CHANGES_REQUESTED** [review]
The changes in this PR look good but there are still areas in the code that are not functioning correctly.

As dh273, “Jump to…” maintenance document “Sub Object Code Global”.
In the “EDIT OBJECT CODES” section of that document both of these are broken.

1. Perform a “Look Up/Add Multiple Object Code Lines” lookup using the magnifying glass icon. On the page that gets presented, attempt to perform a “CG Reporting Code” lookup using the magnifying glass icon. The “CG Reporting Code Lookup” is not presented.
 
2. Perform an Object Code lookup using the magnifying glass icon in that section. On the page that gets presented, attempt to perform a “CG Reporting Code” lookup using the magnifying glass icon.  The “CG Reporting Code Lookup” is not presented.


The SubObjectCodeGlobalEdit business object contains array subObjCdGlobalEditDetails that I am suspecting needs to be converted to the new collections framework in order for the “CG Reporting Code Lookup” contained on the noted “Look Up/Add Multiple Object Code Lines” as well as the “Object Code” lookup in that section to function correctly.

**Comment by db483** [comment]
@nkimble Thank you for spotting this issue. I have added a fix. Please let me know if you find any issues.

**Comment by nkimble** [comment]
Unfortunately, I have found a few more areas that are not working.
As dh273, perform “Jump to…” for the listed maintenance documents and then do the actions described below to see the issues:


1. “Object Code Activation Global”. 
In the “EDIT LIST OF OBJECT CODES” section, perform a “Look Up/Add Multiple Object Code Balance Search Lines” using the magnifying glass.  “Object Code Balance Lookup” is presented. There are two items broken on this page. “CG Reporting Code” lookup with the magnifying glass on the main page is broken. Search results link for “CG Reporting Code” is broken.
 
2. “Sub-Object Code Global Inactivation”. 
In the “LIST OF SUB_OBJECT CODE TO INACTIVATE” section, perform a “Look Up/Add Multiple Sub-Object Code Lines” using the magnifying glass. “Sub-Object Code Lookup” is presented. On that page then do an “Object Code” magnifying glass to present the “Object Code Lookup”.  There are two items broken on this page. “CG Reporting Code” lookup with the magnifying glass on the main page is broken. Search results link for “CG Reporting Code” is broken.
 
3. “Available Balances Lookup”.  
“Object Code” lookup with magnifying glass on that main page goes to “Object Code Lookup” where “CG Reporting Code” lookup with the magnifying glass as well as the search results link for “CG Reporting Code” are both broken.
"Sub-Object Code” lookup with the magnifying glass on that main page goes to the “Sub-Object Code Lookup” which has an “Object Code” lookup with magnifying glass on that sub-page.  That “Object Code Lookup” page has a “CG Reporting Code” lookup with the magnifying glass as well as the search results link for “CG Reporting Code” broken as well.

**Comment by db483** [comment]
Good catch Nancy, I am looking into this. If you find any other issues please report and I will get them sorted in the morning. Thank you.

**Comment by db483** [comment]
This is ready for review again. Please note that for the additional cases reported yesterday, I enable the old lookup and inquiry in order to be able to perform these actions.

**Comment by db483** [comment]
Thank you for reporting that. I will check if I can reproduce the stacktraces

**Comment by db483** [comment]
I am not seeing these exceptions in my local log files. If you have some steps on how to reproduce this that would be very helpful. Thank you.

**Comment by db483** [comment]
@nkimble I created KFSPTS-30301 for converting the remaining lookups/inquiries from “Object Code Activation Global”, “Sub-Object Code Global Inactivation”, and “Available Balances Lookup” to the new framework.

**Pull request merged**
