### PR TITLE
KFSPTS-5434 Add missing customized presentation controller for BA doc

### PR DESCRIPTION
**Pull request by db483**

### CODE REVIEW

**Comment by jhulslander** [comment]
This looks fine, after the the tests run, I will merge this.

**Comment by jhulslander** [comment]
test this please

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
The failing test is a unit test we expect to fail (until another PR is pulled in)  I will merge this.

**Comment by db483** [comment]
Thank you Jay!

**Pull request merged**
