### PR TITLE
Revert "KFSPTS-6361 properly handling acct restriction status code in…

### PR DESCRIPTION
**Pull request by jhulslander**
… account global doc (#624)"

This reverts commit 395f58feb635f7921f4fc62048baec023b3d744f.

Validation found a problem, I need to revert this commit and make more changes.

### CODE REVIEW

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
retest this please

**Comment by db483** [comment]
Andrew, please hold on merging this PR. it may need to be created again so we can get the upgrade one in first
Thank you!

**Comment by db483** [comment]
After further consultation with Chad, I think it will be better to merge this first so that we avoid conflicts when cherry picking to master. Thank you

**Comment by jhulslander** [comment]
retest this please

**Pull request merged**
