### PR TITLE
KFSPTS-31019: Add re-indexing of IWant document after Save action so searches and search results are accurate after data changes.

### PR DESCRIPTION
**Pull request by nkimble**

### CODE REVIEW

**Review by ajd299 — APPROVED** [review]
Code looks good and I couldn't reproduce the error locally on using this branch.

**Comment by ajd299** [comment]
I just noticed this PR is still a draft. Is it okay if we merge it to develop?

**Comment by nkimble** [comment]
@ajd299 I am going to mark it ready for review and re-run the unit tests. If they complete successfully, then the code should be ready to merge.

**Comment by nkimble** [comment]
retest this please

**Comment by nkimble** [comment]
@ajd299 Unit tests have completed successfully.

**Pull request merged**
