### PR TITLE
KFSPTS-17530 Update KFS for running on Java 11

### PR DESCRIPTION
**Pull request by db483**
PR created to test the j11 jenkins unit tests job

### CODE REVIEW

**Comment by db483** [comment]
retest this please

**Comment by cah292** [comment]
The Java 11 unit tests should be fixed now. Let me know whether you want to use this PR for eventually merging these changes to develop, or if you want me to open a separate PR for that instead.

**Comment by db483** [comment]
Thank you Chad, using this PR is fine with me.

**Comment by db483** [comment]
Since I have opened the PR I cannot Approve the changes.

Changes look good and they can be approved and merged by another developer when we are ready to get this in KFS-DEV.

**Pull request merged**
