### PR TITLE
KFSPTS-14298 upgrade to the 12/20/18 and 1/10/19 version of financials

### PR DESCRIPTION
**Pull request by db483**

### CODE REVIEW

**Comment by db483** [comment]
Chad,

Do you have some specific examples in mind when referring to the various attachment download operations? Thank you.

**Comment by cah292** [comment]
I think we would need to test downloading attachments on KFS documents, as well as the template-download action(s) on CGB lookups and the CSV-export feature on Letter of Credit Review Documents.

**Comment by db483** [comment]
Thank you Chad, I have updated the jira with additional information.

**Comment by db483** [comment]
Good questions Chad.

I need some help with the changes related to FINP-4572, I will ping you when you get in.

Regarding the Amazon S3 version of the attachment service, I have checked with KualiCo and they said it is optional and it is disabled by default.

**Pull request merged**
