### PR TITLE
KFSPTS-13258 Final Bill and Billing Period editable

### PR DESCRIPTION
**Pull request by ajd299**
- Make Final Bill and Billing Period editable even if the billing period is expired
- Confirm before submit if the final bill indicator is checked

### CODE REVIEW

**Comment by ajd299** [comment]
screen shot 2019-01-15 at 4 29 53 pm

**Comment by cah292** [comment]
Do you only experience that error with that specific document, or do you see it on other docs as well? Also, have you tried clearing your browser cache or temporarily using a different browser?

**Comment by ajd299** [comment]
Yes I get the same behavior in Firefox and Firefox in-private browsing (new session/cache)

image

**Comment by cah292** [comment]
It looks like there were some impacting changes to the invoiceGeneral.tag file for the 2018-12-13 financials patch. Please make sure you're using the 2018-12-13 patch's version of that file for your overlay. Also, you should rebase your feature branch so that it uses the 2018-12-13 patch code that was recently moved to the develop branch.

**Comment by ajd299** [comment]
It looks like rebasing caused some side effects to this pull request. I noticed a new pull request would only have 5 files changed. Is it okay if we try to disapprove this one and create a new one?

**Comment by cah292** [comment]
Yes, creating a new PR is fine with me. Thanks!

**Pull request closed without merging**
