### PR TITLE
KFSPTS-17081 remove EZRA integration

### PR DESCRIPTION
**Pull request by jhulslander**
This PR removes the EZRA integration code.  There is a related PR that removes the database artifacts: https://github.com/CU-CommunityApps/nonprod-sql/pull/913 .  I checked the Neil B and Chris G, the synonyms aren't used in the warehouse.  Which is good because the synonyms no longer work.

### CODE REVIEW

**Comment by jhulslander** [comment]
retest this pelase

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
retest this please

**Review by cah292 — APPROVED** [review]
Code removal looks good, unit tests pass, and the SQL changes are also good to go. Merging.

**Pull request merged**
