### PR TITLE
KFSPTS-19824: Fix Create Done Batch File Lookup error after 4-30 upgrade due to getPermissionService() call returning null.

### PR DESCRIPTION
**Pull request by nkimble**

### CODE REVIEW

**Comment by nkimble** [comment]
retest

**Comment by nkimble** [comment]
retest this please

**Comment by nkimble** [comment]
retest this please

**Comment by db483** [comment]
retest this please

**Comment by db483** [comment]
retest this please

**Review by db483 — APPROVED** [review]
Changes look good and unit tests pass.

**Pull request merged**
