### PR TITLE
KFSPTS-6105: cleanup our code once sprint 8 contributions are in base…

### PR DESCRIPTION
**Pull request by bhutchinson**
… code

### CODE REVIEW

**Comment by jhulslander** [comment]
retest this please

**Comment by bhutchinson** [comment]
@jhulslander FYI, looks like the tests failed because SciQuest is currently unavailable for maintenance.

**Comment by jhulslander** [comment]
Changes look fine to me.  Should we wait for a good unit test pass before merging?

**Comment by bhutchinson** [comment]
I don't think so, given that the three tests are failing because SciQuest is unavailable for maintenance and not these changes and that that will be the case until noon on Sunday 7/10.

**Comment by jhulslander** [comment]
works for me, will merge

**Comment by bhutchinson** [comment]
thanks

**Pull request merged**
