### PR TITLE
KFSPTS-3599 Add new fields to Account Global doc

### PR DESCRIPTION
**Pull request by db483**

### CODE REVIEW

**Comment by db483** [comment]
retest this please

**Comment by db483** [comment]
This PR is related to PR #143.

**Comment by db483** [comment]
Hi Bryan, I created a new PR for these changes. The unit tests run fine now, both locally and on the PR.

**Comment by bhutchinson** [comment]
Thanks Daniela. The only question I have is if we want to keep all the additional logging you added? If so, maybe it should be debug instead of info?

**Comment by db483** [comment]
Hi Bryan, I think I would like to keep it. If the unit test fails it is easier to figure out what is going on with the logging in place. I will update it to debug.

**Comment by bhutchinson** [comment]
Also, it looks like this branch has conflicts now; maybe you need to rebase from develop?

**Comment by db483** [comment]
I rebased and changed log level. Nancy reverted some changes and that caused some conflicts. Should be all good now.

**Comment by bhutchinson** [comment]
Looks good, thanks Daniela.

**Pull request merged**
