### PR TITLE
KFSPTS-26965 Fix ISO 20022 XML namespacing and char escaping

### PR DESCRIPTION
**Pull request by cah292**
This PR makes a few additional changes to the ISO 20022 file generation:

* Sets up a custom `EscapeHandler` implementation (used by the relevant ISO 20022 Java library) that performs the char escaping (or non-escaping) requested by the new bank. The new class also works around a bug in the library's code that could cause quotes to be duplicated in the ISO 20022 file output.
* Adjusts the file generation to use the Java library's standard means of controlling the XML namespacing in the file output, rather than using KualiCo's string substitution hack.

### CODE REVIEW

**Review by nkimble — COMMENTED** [review]
Changes look good. 

Asking if this makes sense: Should we have a unit test for the new CuEscapeHandler? 
I am not suggesting that it use the data or logic from the JPMC changes. I am asking whether we should have simple happy-path/unhappy-path unit tests with bogus data that exercise the logic we think should be happening within this class to ensure future upgrades do not affect it.

**Comment by cah292** [comment]
The main format extractor class may be too complex to feasibly write unit tests for it, but I agree that the escape handler is simple enough to support some simple tests. I'll look into preparing a few quick test cases for it.

**Comment by cah292** [comment]
I've added some quick unit tests to verify the escape handler's functionality. (Note that in one of the test cases, the `\u00ED` value represents an accented lowercase "i" character.) This is ready for review again.

**Review by nkimble — APPROVED** [review]
Code looks good. Unit tests have passed. My concerns have been addressed. Approving changes and merging to develop branch.

**Pull request merged**
