### PR TITLE
KFSPTS-5522 removing CuPostExpenditureTransactionTest.java as it is h…

### PR DESCRIPTION
**Pull request by jhulslander**
…ighly data sensisitve and does not add much value

### CODE REVIEW

**Comment by jhulslander** [comment]
test this please

**Comment by bhutchinson** [comment]
retest this please

**Comment by bhutchinson** [comment]
code changes look fine; will wait until unit test suite runs clean to merge

**Comment by bhutchinson** [comment]
retest this please

**Comment by jhulslander** [comment]
test this please

**Comment by jhulslander** [comment]
test this please

**Comment by bhutchinson** [comment]
retest this please

**Pull request merged**
