### PR TITLE
KFSPTS-6555: remove doc type that was removed in base

### PR DESCRIPTION
**Pull request by bhutchinson**

### CODE REVIEW

**Comment by jhulslander** [comment]
Year End Depreciation Assets exists in prod, but we don't seem to have used the doc type, and the unit tests pass, so will merge this in.

**Comment by bhutchinson** [comment]
Yeah, it was removed from the dashboard in the latest base code and we don't have any references to it in our project so I figured it was safe to remove. Maybe we want to consider removing the doc type too, but it's probably not causing harm if no one can do anything with it.

**Comment by jhulslander** [comment]
I'd lean toward deactivating it versus remove it just to keep our system as clean as possible.  However, like you mentioned, it's not hurting anything.

**Comment by bhutchinson** [comment]
Good point, thanks.

**Pull request merged**
