### PR TITLE
KFSPTS-21533: FINP-7432 changes from KualiCo patch release 2021-03-11 backported onto original KEW-to-KFS KualiCo patch release 2021-01-28 version of the affected method.

### PR DESCRIPTION
**Pull request by nkimble**

### CODE REVIEW

**Comment by nkimble** [comment]
retest this please

**Comment by jhulslander** [comment]
retest this please

**Comment by jhulslander** [comment]
retest this please

**Review by cah292 — APPROVED** [review]
Changes look good, and unit tests pass. I'm fine with the backport being added as a method override, given how small the change was in base code.

Merging.

**Pull request merged**
